export const CHANGE = 'CHANGE';
export const UNDO = 'UNDO';

export const CART = {
  ITEM_ADD: 'ITEM_ADD'
};

export const SETUP_PAGE = {
  DUELS_PER_DAY_CHANGE: 'DUELS_PER_DAY_CHANGE',
  SEARCHES_PER_DAY_CHANGE: 'SEARCHES_PER_DAY_CHANGE',
  SHIP_ARRIVAL_TIME_CHANGE: 'SHIP_ARRIVAL_TIME_CHANGE',
  ADD_CHARACTER: 'ADD_CHARACTER',
  REMOVE_CHARACTER: 'REMOVE_CHARACTER',
  START_GAME: 'START_GAME'
};

export const GAME = {
  BUTTON_CLICKED: 'BUTTON_CLICKED',
  SET_INPUT: 'SET_INPUT',
  LEAVE_FILTERED: 'LEAVE_FILTERED',
};
